name = "Hugo Theme Take Notes"
license = "MIT"
licenselink = "https://github.com/shichaoxia/hugo-theme-take-notes/blob/main/LICENSE"
description = "A Hugo theme that focuses on taking notes"

homepage = "https://github.com/shichaoxia/hugo-theme-take-notes"

demosite = "https://hugo-theme-take-notes-example.pages.dev/"

tags = ["responsive", "simple", "blog", "take-notes", "search"]
features = ["table-of-contents", "book-cover", "tailwindcss", "responsive", "search"]

min_version = "0.83.0"

[author]
  name = "Shichao Xia"
  homepage = "https://github.com/shichaoxia"
